#BOARD_TAG    = uno
#BOARD_TAG    = leonardo
BOARD_TAG = mega2560
ARDUINO_LIBS =  Bit SoftwareServo Servo PString

MONITOR_PORT = /dev/cu.usbmodem1411
#MONITOR_BAUDRATE = 9600

include $(ARDMK_DIR)/Arduino.mk
